name = "Epidemics"
uuid = "3842d2e4-6389-40c1-b4a0-39a6a39a1f90"
authors = ["Pratik Gupte"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
