name = "Epidemics"
uuid = "3842d2e4-6389-40c1-b4a0-39a6a39a1f90"
authors = ["Pratik Gupte <pratikgupte16@gmail.com> and contributors"]
version = "0.0.9"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
